# Read more on https://github.com/amannn/action-semantic-pull-request
name: 'PR Title Check'

on:
  pull_request:
    branches: [master,production]
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
